on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action"
        id: "todo"
        with:
          AUTO_ASSIGN: true
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
